---
- name: Installing AWS required packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages }}"
  when: required_packages

- name: Downloading Pip
  get_url:
    url: "{{ pip_url }}"
    dest: "/tmp/{{ pip_url | basename }}"
    force_basic_auth: no
    mode: 0600

- name: Installing Pip
  become: yes
  command: "python {{ pip_url | basename }}"
  args:
    chdir: "/tmp"

- name: Downgrading Pip to version 9
  become: yes
  command: "pip install pip==9.0.3"

- name: Installing AWS required pip packages
  become: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_packages }}"
  when: pip_packages
...
